FROM nginx:latest

# Install all packages
RUN apt-get update && \
    apt-get install dnsmasq -y  && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir /service

# Step 1 - Production config
COPY nginx/                        /etc/nginx/

# Test setup

# Step 2 - we can not directly copy it to /etc/hosts since docker will
# regenerate the file and overwrite our changes. We will copy content from
# /etc/test.hosts to /etc/hosts on runtime in launch.sh script
COPY tests/hosts/hosts                /etc/test.hosts

# Step 3
COPY tests/nginx                      /etc/nginx/

# Step 4
COPY tests/ssl/nginx-selfsigned.crt   /etc/ssl/certs/nginx-selfsigned.crt
COPY tests/ssl/nginx-selfsigned.key   /etc/ssl/private/nginx-selfsigned.key

COPY tests/launch.sh /service/

WORKDIR /service
ENTRYPOINT ["./launch.sh"]

STOPSIGNAL SIGQUIT
