version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.tests
    cap_add:
      - NET_ADMIN
    ports:
     - "81:80"
    volumes: 
     - ${PWD}/nginx/conf.d/api-gateway.conf:/etc/nginx/conf.d/api-gateway.conf
